echo "grep "a" Makefile test_grep.txt > txt1.txt && ./s21_grep "a" Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -e "[ap]" Makefile test_grep.txt > txt1.txt && ./s21_grep -e "[ap]" Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -i "P" Makefile test_grep.txt > txt1.txt && ./s21_grep -i "P" Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -v "M" Makefile test_grep.txt > txt1.txt && ./s21_grep -v "M" Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -c "." Makefile test_grep.txt > txt1.txt && ./s21_grep -c "." Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -l "a" Makefile test_grep.txt > txt1.txt && ./s21_grep -l "a" Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -n "21" Makefile test_grep.txt > txt1.txt && ./s21_grep -n "21" Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -h "." Makefile test_grep.txt > txt1.txt && ./s21_grep -h "." Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -s "21" Makefile test_grep.txt > txt1.txt && ./s21_grep -s "21" Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -o "a" Makefile test_grep.txt > txt1.txt && ./s21_grep -o "a" Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"

echo "grep "[ap]" Makefile  > txt1.txt && ./s21_grep "[ap]" Makefile > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -e "[ap]" Makefile  > txt1.txt && ./s21_grep -e "[ap]" Makefile > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -i "P" Makefile  > txt1.txt && ./s21_grep -i "P" Makefile  > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -v "M" Makefile  > txt1.txt && ./s21_grep -v "M" Makefile  > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -c "." Makefile  > txt1.txt && ./s21_grep -c "." Makefile  > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -l "a" Makefile  > txt1.txt && ./s21_grep -l "a" Makefile  > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -n "21" Makefile > txt1.txt && ./s21_grep -n "21" Makefile  > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -h "." Makefile  > txt1.txt && ./s21_grep -h "." Makefile  > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -s "21" Makefile  > txt1.txt && ./s21_grep -s "21" Makefile  > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -o "[al]" Makefile > txt1.txt && ./s21_grep -o "[al]" Makefile > txt2.txt && diff -s txt1.txt txt2.txt"

echo "grep -f f_flag.txt Makefile test_grep.txt > txt1.txt && ./s21_grep -f f_flag.txt Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -f f_flag.txt Makefile > txt1.txt && ./s21_grep -f f_flag.txt Makefile > txt2.txt && diff -s txt1.txt txt2.txt"
echo "grep -f f_flag.txt Makefile test_grep.txt > txt1.txt && ./s21_grep -f f_flag.txt Makefile test_grep.txt > txt2.txt && diff -s txt1.txt txt2.txt"